color_bg="black"
color_bg_all="#99AA38"
color_fg_default="colour16"
color_fg_alt="#E5E9F0"
color_bg_alt="#3B4252"
color_bg_highlight="#14591D"
color_fg_highlight="#ACD2ED"

color_win_current_bg="brightgreen"
color_win_current_fg="black"

color_session_text_bg="brightred"
color_session_text_fg="#ffffff"
color_session_icon_bg="red"
color_session_icon_fg="#ffffff"

color_calendar_icon_bg="orange"
color_calendar_icon_fg="#000000"
color_calendar_text_bg="yellow"
color_calendar_text_fg="#000000"

color_clock_icon_bg="blue"
color_clock_icon_fg="#143642"
color_clock_text_bg="brightblue"
color_clock_text_fg="#ffffff"

color_user_icon_bg="magenta"
color_user_icon_fg="#5E2750"
color_user_text_bg="brightmagenta"
color_user_text_fg="#ffffff"
