color_bg="#434C5E"
color_bg_all="#99AA38"
color_fg_default="colour16"
color_fg_alt="#E5E9F0"
color_bg_alt="#3B4252"
color_bg_highlight="#14591D"
color_fg_highlight="#ACD2ED"

color_win_current_bg="#A3BE8C"
color_win_current_fg="#ffffff"

color_session_text_bg="#BF616A"
color_session_text_fg="#ffffff"
color_session_icon_bg="#aa4752"
color_session_icon_fg="#ffffff"

color_calendar_icon_bg="#D08770"
color_calendar_icon_fg="#000000"
color_calendar_text_bg="#EBCB8B"
color_calendar_text_fg="#000000"

color_clock_icon_bg="#81A1C1"
color_clock_icon_fg="#143642"
color_clock_text_bg="#8FBCBB"
color_clock_text_fg="#ffffff"

color_user_icon_bg="#8c6e8f"
color_user_icon_fg="#5E2750"
color_user_text_bg="#B48EAD"
color_user_text_fg="#ffffff"
